#!/usr/bin/env python3
"""Maintain the project filetree manifest and rendered summary.

This script intentionally uses only the Python standard library plus git so it
can run in Codex automations without extra project dependencies.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[2]
MANIFEST_PATH = ROOT / ".claude" / "filetree" / "manifest.json"
FILETREE_PATH = ROOT / ".claude" / "filetree" / "FILETREE.md"
GENERATED_PATHS = {
    ".claude/filetree/manifest.json",
    ".claude/filetree/FILETREE.md",
}

SCHEMA_VERSION = 1


AREA_ORDER = [
    "workspace",
    "crates",
    "node",
    "docs",
    "scripts",
    "configuration",
    "codex",
    "agents",
    "other",
]

AREA_TITLES = {
    "workspace": "Workspace",
    "crates": "Crates",
    "node": "Node",
    "docs": "Docs",
    "scripts": "Scripts",
    "configuration": "Configuration",
    "codex": "Codex",
    "agents": "Agents",
    "other": "Other",
}


DESCRIPTION_OVERRIDES = {
    ".claude/AGENTS.md": [
        "Per-directory rules for the .claude/ harness-config tree (settings, hooks, scripts, agents, skills, commands).",
        "Defines the SessionStart hook contract and the boundary between harness config and source code.",
    ],
    ".claude/agents/filetree-reviewer.md": [
        "Subagent definition for reviewing stale filetree descriptions.",
        "Restricts writes to .claude/filetree/manifest.json and .claude/filetree/FILETREE.md.",
    ],
    ".claude/agents/haskell-reference-auditor.md": [
        "Subagent definition for mapping Rust behavior to the IntersectMBO/cardano-node Haskell reference.",
        "Read-heavy specialist for protocol, ledger, Plutus, network, and storage parity comparison.",
    ],
    ".claude/commands/filetree-check.md": [
        "Slash command running python .claude/scripts/filetree.py check.",
        "Reports stale entries against .claude/filetree/manifest.json.",
    ],
    ".claude/commands/parity-check.md": [
        "Slash command running python scripts/check-parity-matrix.py.",
        "Validates docs/parity-matrix.json against the local Rust and Haskell trees.",
    ],
    ".claude/commands/parity-plan.md": [
        "Slash command authoring a parity-plan template before substantive code edits.",
        "Mirrors the Codex-style autoplanning gate for protocol-sensitive work.",
    ],
    ".claude/filetree/FILETREE.md": [
        "Generated human-readable file inventory rendered from the filetree manifest.",
        "Self-exempt from recursive freshness checks because it is regenerated by the filetree script.",
    ],
    ".claude/filetree/manifest.json": [
        "Machine-readable source of truth for file descriptions and freshness metadata.",
        "Self-exempt from recursive freshness checks because it stores generated filetree state.",
    ],
    ".claude/hooks/session-start.sh": [
        "Claude Code SessionStart hook that provisions the pinned Rust toolchain on remote sessions.",
        "Gated on $CLAUDE_CODE_REMOTE; idempotent; non-mutating; emits a JSON async preamble on the first line.",
    ],
    ".claude/scripts/filetree.py": [
        "Stdlib-only maintenance tool for scanning, rendering, checking, and accepting filetree metadata.",
        "Used by the cardano-filetree-maintainer skill and the filetree-reviewer subagent.",
    ],
    ".claude/settings.json": [
        "Project-scoped Claude Code settings (committed): permissions allow-list, env vars, hooks.",
        "Loads after ~/.claude/settings.json and is overridden by .claude/settings.local.json (gitignored).",
    ],
    ".claude/skills/cardano-filetree-maintainer/SKILL.md": [
        "Repo-local skill for reviewing stale filetree entries and refreshing their descriptions.",
        "Limits maintenance work to stale files plus generated filetree metadata.",
    ],
    ".claude/skills/continuous-agent-loop/SKILL.md": [
        "Repo-local skill for the continuous-agent loop pattern used during long parity arcs.",
        "Coordinates round-by-round development with the operational-runs docs trail.",
    ],
    ".gitattributes": [
        "Repository line-ending and text normalization rules.",
        "Keeps generated and source files stable across Windows and Unix tooling.",
    ],
    ".gitignore": [
        "Ignore rules for build outputs, local caches, vendored Haskell reference source, and operator artifacts.",
        "Keeps heavyweight generated artifacts and secrets out of version control.",
    ],
    "AGENTS.md": [
        "Top-level workspace rules + rolling parity journal for Yggdrasil contributors.",
        "Defines upstream-reference expectations, command gates, autoplanning, and the parity-matrix gate.",
    ],
    "Cargo.lock": [
        "Pinned Rust dependency lockfile for reproducible workspace builds.",
        "Captures exact transitive crate versions resolved for this repository.",
    ],
    "Cargo.toml": [
        "Root Cargo workspace manifest defining members, shared metadata, dependency versions, lints.",
        "Pins the workspace at edition 2024 with rustc 1.95.0 and -D warnings via [workspace.lints.clippy].",
    ],
    "CLAUDE.md": [
        "Claude Code project guidance: parity rules, command aliases, AGENTS.md index, .reference-haskell-cardano-node layout.",
        "Authoritative when in conflict with the default Claude Code system prompt.",
    ],
    "README.md": [
        "Top-level project overview for Yggdrasil — the pure-Rust Cardano node port.",
        "Summarizes goals, parity targets, current status, architecture, setup, and validation commands.",
    ],
    "docs/parity-matrix.json": [
        "Machine-readable parity-status inventory for Rust ↔ IntersectMBO/cardano-node features.",
        "Validated by scripts/check-parity-matrix.py; the reference.tag tracks the latest upstream release (currently 11.0.1).",
    ],
    "docs/operational-runs/2026-05-12-round-498-plan-sync-rs-split-arc.md": [
        "Historical R498-R510 sync split plan, now reflected in crates/node/sync/ and adjacent runtime crates.",
        "Kept as operational evidence; current instructions live in the crate AGENTS.md files.",
    ],
    "docs/operational-runs/archive/2026-05-09-round-279-runtime-naming-parity.md": [
        "Historical runtime naming-parity sweep, now represented by crates/node/runtime/.",
        "Kept as archived operational evidence; current instructions live in crates/node/runtime/AGENTS.md.",
    ],
    "rust-toolchain.toml": [
        "Rust toolchain pin for consistent compiler, formatter, and clippy behavior.",
        "Ensures contributors and automation use the same channel and components.",
    ],
    "scripts/check-parity-matrix.py": [
        "Stdlib-only validator for docs/parity-matrix.json schema, status, and on-disk paths.",
        "Bumps tag policy via REFERENCE_TAG; current target is 11.0.1.",
    ],
    "scripts/check-reference-artifacts.py": [
        "Linux/WSL local validator for the vendored Haskell cardano-node install tree.",
        "Checks executable reference binaries, network share bundles, and cardano-node version policy.",
    ],
    "scripts/check-stale-placement.py": [
        "Stdlib-only validator for stale post-reorganization source, config, script, and skill paths.",
        "Scans current non-historical surfaces while excluding changelog and operational-run evidence.",
    ],
    "scripts/setup-reference.sh": [
        "Recreates the metadata-free .reference-haskell-cardano-node/ source snapshot and optional Linux install.",
        "Default CARDANO_NODE_VERSION is 11.0.1; --sources-only skips the Linux binary bundle.",
    ],
}


def run_git(args: list[str], *, check: bool = True) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        ["git", *args],
        cwd=ROOT,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        check=check,
    )


def utc_now() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z")


def rel(path: Path) -> str:
    return path.relative_to(ROOT).as_posix()


def read_text_sample(path: Path, max_bytes: int = 65536) -> str:
    try:
        raw = path.read_bytes()[:max_bytes]
    except OSError:
        return ""
    return raw.decode("utf-8", errors="replace")


def git_ls_files() -> list[str]:
    result = run_git(["ls-files", "--cached", "--others", "--exclude-standard", "-z"])
    paths = [p for p in result.stdout.split("\0") if p]
    for generated in GENERATED_PATHS:
        if (ROOT / generated).exists() or generated.endswith("manifest.json") or generated.endswith("FILETREE.md"):
            paths.append(generated)
    current = set()
    for path in paths:
        normalized = path.replace("\\", "/")
        if not normalized:
            continue
        if normalized in GENERATED_PATHS or (ROOT / normalized).is_file():
            current.add(normalized)
    return sorted(current)


def sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()


def git_blob_hash(path: str) -> str:
    full = ROOT / path
    if not full.exists() or not full.is_file():
        return ""
    result = run_git(["hash-object", "--", path], check=False)
    return result.stdout.strip() if result.returncode == 0 else ""


def file_metadata(path: str) -> dict[str, Any]:
    full = ROOT / path
    if not full.exists() or not full.is_file():
        return {
            "content_sha256": "",
            "git_blob": "",
            "source_mtime_ns": 0,
        }
    stat = full.stat()
    return {
        "content_sha256": sha256_file(full),
        "git_blob": git_blob_hash(path),
        "source_mtime_ns": stat.st_mtime_ns,
    }


def normalize_description(lines: Any) -> list[str]:
    if not isinstance(lines, list):
        return []
    cleaned = []
    for line in lines[:2]:
        if isinstance(line, str):
            text = " ".join(line.strip().split())
            if text:
                cleaned.append(text)
    return cleaned


def sentence(text: str) -> str:
    text = " ".join(text.strip().split())
    if not text:
        return ""
    if text[-1] not in ".!?":
        text += "."
    return text


def markdown_description(path: str, text: str) -> list[str]:
    lines = [line.strip() for line in text.splitlines()]
    heading = ""
    paragraph = ""

    for line in lines:
        if line.startswith("#"):
            heading = line.lstrip("#").strip()
            break

    in_code = False
    for line in lines:
        if line.startswith("```"):
            in_code = not in_code
            continue
        if in_code or not line or line.startswith("#") or line.startswith("[!") or line.startswith("|"):
            continue
        if line.startswith("- ") or line.startswith("* "):
            paragraph = line[2:].strip()
            break
        paragraph = line
        break

    if heading and paragraph:
        return [sentence(f"{heading}: {paragraph}")[:180]]
    if heading:
        return [sentence(f"Markdown documentation for {heading}")[:180]]
    return [f"Markdown documentation file at {path}."]


def rust_description(path: str, text: str) -> list[str]:
    docs = []
    for raw in text.splitlines()[:80]:
        line = raw.strip()
        if line.startswith("//!"):
            body = line[3:].strip()
        elif line.startswith("///"):
            body = line[3:].strip()
        elif line.startswith("//"):
            body = line[2:].strip()
        elif line.startswith("#![") or line.startswith("#[") or not line:
            continue
        else:
            break
        if body and not body.startswith("Copyright"):
            docs.append(body)
        if len(" ".join(docs)) > 140:
            break

    if docs:
        return [sentence(" ".join(docs))[:180]]

    parts = path.split("/")
    name = Path(path).stem.replace("_", " ")
    if parts[:2] == ["node", "src"]:
        return [f"Rust source for node-level {name} behavior."]
    if len(parts) >= 4 and parts[0] == "crates" and parts[2] == "src":
        crate = parts[1].replace("cardano-", "")
        return [f"Rust source for the {crate} crate's {name} module."]
    if "/tests/" in path:
        return [f"Rust integration or regression tests for {name} behavior."]
    if "/benches/" in path:
        return [f"Rust benchmark source for {name} behavior."]
    return [f"Rust source file for {name} behavior."]


def cargo_toml_description(path: str, text: str) -> list[str]:
    if path == "Cargo.toml":
        return DESCRIPTION_OVERRIDES[path]
    crate = path.split("/")[1] if path.startswith("crates/") and "/" in path else Path(path).parent.name
    return [
        f"Cargo manifest for the {crate} crate.",
        "Declares crate metadata, dependencies, features, and local lint behavior.",
    ]


def json_description(path: str) -> list[str]:
    name = Path(path).name
    stem = Path(path).stem
    parts = path.split("/")

    if path == "deny.toml":
        return ["Cargo-deny policy for auditing licenses, advisories, duplicate crates, and dependency bans."]

    if parts and parts[0] == "configuration":
        network = parts[1] if len(parts) > 2 else "network"
        readable_network = network.replace("-", " ")
        if "genesis" in name:
            return [
                f"Cardano {readable_network} genesis configuration used by node startup and tests.",
                "Kept concise in the filetree because the JSON payload is large protocol data.",
            ]
        if "topology" in name:
            return [f"Peer topology configuration for Cardano {readable_network} network connectivity."]
        if "config" in name:
            return [
                f"Runtime node configuration for Cardano {readable_network}.",
                "Includes protocol, tracing, socket, and ledger-related settings consumed by the node.",
            ]
        if "checkpoints" in name:
            return [f"Known chain checkpoint data for Cardano {readable_network} synchronization validation."]
        if "peer-snapshot" in name:
            return [f"Peer snapshot data used for Cardano {readable_network} network bootstrap behavior."]
        if "submit-api" in name:
            return [f"Submit API configuration for Cardano {readable_network} transaction submission flows."]
        if "tracer" in name:
            return [f"Tracing configuration for Cardano {readable_network} node observability."]
        return [f"Cardano {readable_network} configuration JSON data file: {name}."]

    if "test" in path or "fixture" in path:
        return [f"JSON fixture data for {stem.replace('-', ' ').replace('_', ' ')} tests."]
    return [f"JSON data file for {stem.replace('-', ' ').replace('_', ' ')}."]


def toml_description(path: str, text: str) -> list[str]:
    if path in DESCRIPTION_OVERRIDES:
        return DESCRIPTION_OVERRIDES[path]
    if path.endswith("Cargo.toml"):
        return cargo_toml_description(path, text)
    stem = Path(path).stem.replace("_", " ").replace("-", " ")
    return [f"TOML configuration file for {stem}."]


def default_description(path: str) -> list[str]:
    if path in DESCRIPTION_OVERRIDES:
        return DESCRIPTION_OVERRIDES[path]

    full = ROOT / path
    text = read_text_sample(full)
    suffix = Path(path).suffix.lower()

    if suffix == ".rs":
        return rust_description(path, text)
    if suffix == ".md":
        return markdown_description(path, text)
    if suffix == ".toml":
        return toml_description(path, text)
    if suffix == ".json":
        return json_description(path)
    if suffix == ".lock":
        return DESCRIPTION_OVERRIDES.get(path, [f"Lockfile for {Path(path).stem} dependencies."])
    if suffix in {".sh", ".ps1"}:
        return [f"Shell helper script for {Path(path).stem.replace('-', ' ').replace('_', ' ')} workflows."]
    if suffix in {".bin", ".dat"}:
        return [f"Binary fixture data for {Path(path).stem.replace('-', ' ').replace('_', ' ')}."]
    if suffix in {".golden", ".out"}:
        return [f"Golden output fixture for {Path(path).stem.replace('-', ' ').replace('_', ' ')} tests."]

    return [f"Project file at {path}."]


def make_entry(path: str, existing: dict[str, Any] | None = None, *, accept_current: bool) -> dict[str, Any]:
    existing = existing or {}
    if path in DESCRIPTION_OVERRIDES:
        description = DESCRIPTION_OVERRIDES[path]
    else:
        description = normalize_description(existing.get("description_lines")) or default_description(path)
    description = normalize_description(description) or [f"Project file at {path}."]

    metadata = file_metadata(path) if accept_current else {
        "content_sha256": existing.get("content_sha256", ""),
        "git_blob": existing.get("git_blob", ""),
        "source_mtime_ns": existing.get("source_mtime_ns", 0),
    }

    if accept_current or "described_at_utc" not in existing:
        described_at = utc_now()
    else:
        described_at = existing.get("described_at_utc", "")

    return {
        "path": path,
        "description_lines": description[:2],
        "content_sha256": metadata.get("content_sha256", ""),
        "git_blob": metadata.get("git_blob", ""),
        "source_mtime_ns": int(metadata.get("source_mtime_ns", 0) or 0),
        "described_at_utc": described_at,
        "generated_self_exempt": path in GENERATED_PATHS,
    }


def load_manifest() -> dict[str, Any]:
    if not MANIFEST_PATH.exists():
        return {"schema_version": SCHEMA_VERSION, "files": []}
    try:
        data = json.loads(MANIFEST_PATH.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise SystemExit(f"failed to read manifest: {exc}") from exc
    if not isinstance(data, dict):
        raise SystemExit("manifest must be a JSON object")
    if not isinstance(data.get("files"), list):
        data["files"] = []
    return data


def write_manifest(entries: list[dict[str, Any]]) -> None:
    MANIFEST_PATH.parent.mkdir(parents=True, exist_ok=True)
    payload = {
        "schema_version": SCHEMA_VERSION,
        "generated_at_utc": utc_now(),
        "description_policy": "Each entry has one or two concise human-maintained description lines. Run accept-current after reviewing stale entries.",
        "files": sorted(entries, key=lambda item: item["path"]),
    }
    MANIFEST_PATH.write_text(
        json.dumps(payload, indent=2, ensure_ascii=True) + "\n",
        encoding="utf-8",
        newline="\n",
    )


def manifest_entries_by_path(manifest: dict[str, Any]) -> dict[str, dict[str, Any]]:
    by_path = {}
    for item in manifest.get("files", []):
        if isinstance(item, dict) and isinstance(item.get("path"), str):
            by_path[item["path"]] = item
    return by_path


def scan(*, write: bool) -> list[dict[str, Any]]:
    manifest = load_manifest()
    existing = manifest_entries_by_path(manifest)
    entries = [make_entry(path, existing.get(path), accept_current=path not in existing) for path in git_ls_files()]
    if write:
        write_manifest(entries)
        render()
    return entries


def accept_current() -> None:
    manifest = load_manifest()
    existing = manifest_entries_by_path(manifest)
    entries = [make_entry(path, existing.get(path), accept_current=True) for path in git_ls_files()]
    write_manifest(entries)
    render()


def area_for(path: str) -> str:
    top = path.split("/", 1)[0]
    if top == "crates":
        return "crates"
    if top == "node":
        return "node"
    if top == "docs":
        return "docs"
    if top == "scripts":
        return "scripts"
    if top == "configuration":
        return "configuration"
    if top == ".codex":
        return "codex"
    if top == ".agents":
        return "agents"
    if "/" not in path:
        return "workspace"
    return "other"


def render() -> None:
    manifest = load_manifest()
    entries = sorted(manifest_entries_by_path(manifest).values(), key=lambda item: item["path"])
    grouped: dict[str, list[dict[str, Any]]] = {area: [] for area in AREA_ORDER}
    for entry in entries:
        grouped.setdefault(area_for(entry["path"]), []).append(entry)

    lines = [
        "# Project Filetree",
        "",
        "> Generated from `.claude/filetree/manifest.json` by `.claude/scripts/filetree.py render`.",
        "> Update descriptions in the manifest, then run `python .claude/scripts/filetree.py accept-current`.",
        "",
        f"- Schema version: {manifest.get('schema_version', SCHEMA_VERSION)}",
        f"- Generated at: {utc_now()}",
        f"- Files described: {len(entries)}",
        "",
    ]

    for area in AREA_ORDER:
        items = grouped.get(area) or []
        if not items:
            continue
        lines.extend([f"## {AREA_TITLES.get(area, area.title())}", ""])
        for entry in items:
            lines.append(f"- `{entry['path']}`")
            for desc in normalize_description(entry.get("description_lines")):
                lines.append(f"  - {desc}")
            if entry.get("generated_self_exempt"):
                lines.append("  - Freshness: generated self-exempt.")
        lines.append("")

    FILETREE_PATH.parent.mkdir(parents=True, exist_ok=True)
    FILETREE_PATH.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8", newline="\n")


def current_path_set() -> set[str]:
    return set(git_ls_files())


def check_manifest() -> int:
    manifest = load_manifest()
    existing = manifest_entries_by_path(manifest)
    current = current_path_set()
    findings: list[str] = []

    for path in sorted(current - set(existing)):
        findings.append(f"NEW {path}: file is not present in manifest")

    for path in sorted(set(existing) - current):
        findings.append(f"REMOVED {path}: manifest entry has no current repository file")

    for path in sorted(current & set(existing)):
        entry = existing[path]
        if entry.get("generated_self_exempt"):
            continue
        metadata = file_metadata(path)
        reasons = []
        if entry.get("content_sha256") != metadata["content_sha256"]:
            reasons.append("content_sha256 changed")
        if entry.get("git_blob") != metadata["git_blob"]:
            reasons.append("git_blob changed")
        if reasons:
            old_mtime = entry.get("source_mtime_ns", 0)
            new_mtime = metadata["source_mtime_ns"]
            findings.append(f"STALE {path}: {', '.join(reasons)}; mtime_ns {old_mtime} -> {new_mtime}")

    if findings:
        print("Filetree check found entries requiring review:")
        for finding in findings:
            print(f"- {finding}")
        return 1

    print("Filetree check clean: all non-exempt entries match accepted metadata.")
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Maintain Codex filetree manifest and rendered inventory.")
    subparsers = parser.add_subparsers(dest="command", required=True)

    scan_parser = subparsers.add_parser("scan", help="Scan repository files and optionally write missing manifest entries.")
    scan_parser.add_argument("--write", action="store_true", help="Write manifest entries while preserving existing descriptions and metadata.")

    subparsers.add_parser("render", help="Render FILETREE.md from manifest.json.")
    subparsers.add_parser("check", help="Report new, removed, changed, or stale filetree entries.")
    subparsers.add_parser("accept-current", help="Accept current file content metadata after descriptions have been reviewed.")

    args = parser.parse_args(argv)

    os.chdir(ROOT)
    if args.command == "scan":
        entries = scan(write=args.write)
        if not args.write:
            print(f"Scanned {len(entries)} files.")
        return 0
    if args.command == "render":
        render()
        return 0
    if args.command == "check":
        return check_manifest()
    if args.command == "accept-current":
        accept_current()
        return 0
    return 2


if __name__ == "__main__":
    raise SystemExit(main())
